version: "3.0"

services:
    nodered:
        image: eduartrobotik/eduart-nodered:0.1.0
        container_name: eduart-nodered-0.1.0
        user: root
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        network_mode: host
        volumes:
            # - node_red_data:/data:rw
            - node_red_data:/home/user/:rw

volumes:
    node_red_data:
